name: CD
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i $SSH_PRIVATE_KEY azureuser@FastAPI-Server \
          "cd /home/azureuser/fastapi-app && \
          git pull && \
          sudo systemctl restart fastapi"