name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Render
      uses: render-actions/deploy@v1
      with:
        service-id: your-render-service-id
        api-key: ${{ secrets.RENDER_API_KEY }}