name: CD
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Disable Strict Host Key Checking
        run: |
          mkdir -p ~/.ssh
          echo "Host 20.185.80.28
                StrictHostKeyChecking no
                UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key azureuser@20.185.80.28 "
          cd /home/azureuser/fastapi-app && \
          git pull && \
          sudo systemctl restart fastapi"
